[package]
name = "first"
version = "0.1.0"
authors = ["Jun Kimura <junkxdev@gmail.com>"]
edition = "2018"

[dependencies]
hmcdk = { path = "../../../../bluele/hypermint/hmcdk/lib" }

[dev-dependencies]
hmemu = { path = "../.." }

[lib]
crate-type = ["cdylib"]
