[package]
name = "first"
version = "0.1.0"
authors = ["Jun Kimura <junkxdev@gmail.com>"]
edition = "2018"

[dependencies]
hmc = { git = "https://github.com/bluele/hypermint", tag = "v0.3.0" }

[dev-dependencies]
hmemu = { path = "../.." }

[lib]
crate-type = ["cdylib"]
